### ISSUE TITLE
dbclient-2.1.0 throws missing index error even when index exists

### ISSUE THREAD

**Issue by orangejulius** [pelias/dbclient#47]
Some time ago we added a feature to [detect if the pelias index exists](https://github.com/pelias/dbclient/pull/38) before starting imports. It looks like this isn't working, at least on my machine.

```
julian@julian-mapzen ~/repos/pelias/openstreetmap $ curl http://localhost:9200/_cat/indices?v=1
health status index  pri rep docs.count docs.deleted store.size pri.store.size 
green  open   pelias   1   0          0            0       159b           159b 
julian@julian-mapzen ~/repos/pelias/openstreetmap $ npm start

> pelias-openstreetmap@0.0.0-semantic-release start /home/julian/repos/pelias/openstreetmap
> node --max_old_space_size=4096 index.js

2017-06-19T19:50:16.183Z - info: [openstreetmap] imports.openstreetmap.adminLookup has been deprecated, enable adminLookup using imports.adminLookup.enabled = true
2017-06-19T19:50:16.555Z - info: [openstreetmap] Creating read stream for: /home/julian/data/osm/helsinki_finland.osm.pbf
ERROR: Elasticsearch index pelias does not exist
You must use the pelias-schema tool (https://github.com/pelias/schema/) to create the index first
For full instructions on setting up Pelias, see http://pelias.io/install.html
/home/julian/repos/pelias/openstreetmap/node_modules/pelias-dbclient/src/configValidation.js:38
          throw new Error(`elasticsearch index ${config.schema.indexName} does not exist`);
          ^

Error: elasticsearch index pelias does not exist
    at existsCallback (/home/julian/repos/pelias/openstreetmap/node_modules/pelias-dbclient/src/configValidation.js:38:17)
    at respond (/home/julian/repos/pelias/openstreetmap/node_modules/elasticsearch/src/lib/transport.js:310:9)
    at checkRespForFailure (/home/julian/repos/pelias/openstreetmap/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/home/julian/repos/pelias/openstreetmap/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/home/julian/repos/pelias/openstreetmap/node_modules/lodash/lodash.js:4968:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.4.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/home/julian/bin/npm" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pelias-openstreetmap@0.0.0-semantic-release start: `node --max_old_space_size=4096 index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pelias-openstreetmap@0.0.0-semantic-release start script 'node --max_old_space_size=4096 index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pelias-openstreetmap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=4096 index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pelias-openstreetmap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pelias-openstreetmap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/julian/repos/pelias/openstreetmap/npm-debug.log
```

**Comment by tigerlily-he** [comment]
Same error when I run this on OSX in Docker

**Comment by missinglink** [comment]
from a quick glance at the code it appears that the `esclient.indices.exists()` call is non-blocking and so will race other `esclient.*` calls. producing non-deterministic error messages.

**Comment by orangejulius** [comment]
It turns out it was just a mismatch between what we expected the callback's parameters would be and what they actually are. Most likely a newer version of the `elasticsearch-js` module changed the order of these params to match the normal `(err, response)` format that mode node.js callback conform to.
